<?php
return array (
  'zuidam3u8' => 
  array (
    'status' => '1',
    'from' => 'zuidam3u8',
    'show' => '【极速线】',
    'des' => '',
    'ps' => '1',
    'parse' => '//z1.m1907.cn/?jx=',
    'sort' => '1000',
    'tip' => '在线播放,无需安装播放器',
    'id' => 'zuidam3u8',
  ),
  'ckplayer' => 
  array (
    'status' => '1',
    'sort' => '908',
    'from' => 'ckplayer',
    'show' => 'CkPlayer-H5播放器',
    'des' => 'ckplayer.com',
    'parse' => '',
    'ps' => '0',
    'tip' => '无需安装任何插件',
    'id' => 'ckplayer',
  ),
  'iva' => 
  array (
    'status' => '1',
    'sort' => '906',
    'from' => 'iva',
    'show' => 'H5自带解析',
    'des' => 'videojj.com',
    'ps' => '0',
    'parse' => '',
    'tip' => '无需安装任何插件',
    'id' => 'iva',
  ),
  'iframe' => 
  array (
    'status' => '1',
    'sort' => '905',
    'from' => 'iframe',
    'show' => 'iframe外链数据',
    'des' => 'iframe外链数据',
    'parse' => '',
    'ps' => '0',
    'tip' => '无需安装任何插件',
    'id' => 'iframe',
  ),
  'link' => 
  array (
    'status' => '1',
    'sort' => '904',
    'from' => 'link',
    'show' => '外链数据',
    'des' => '外部网站播放链接',
    'ps' => '0',
    'parse' => '',
    'tip' => '无需安装任何插件',
    'id' => 'link',
  ),
  '56_' => 
  array (
    'status' => '1',
    'sort' => '617',
    'from' => '56_',
    'show' => '我乐视频',
    'des' => '56.com',
    'parse' => '',
    'ps' => '1',
    'tip' => '无需安装任何插件',
    'id' => '56_',
  ),
  'tudou' => 
  array (
    'status' => '1',
    'sort' => '616',
    'from' => 'tudou',
    'show' => '土豆视频',
    'des' => 'tudou.com',
    'parse' => '',
    'ps' => '1',
    'tip' => '无需安装任何插件',
    'id' => 'tudou',
  ),
  'ku6' => 
  array (
    'status' => '1',
    'sort' => '615',
    'from' => 'ku6',
    'show' => '酷6视频',
    'des' => 'ku6.com',
    'parse' => '',
    'ps' => '1',
    'tip' => '无需安装任何插件',
    'id' => 'ku6',
  ),
  'joy' => 
  array (
    'status' => '1',
    'sort' => '612',
    'from' => 'joy',
    'show' => '激动网',
    'des' => 'joy.cn',
    'parse' => '',
    'ps' => '1',
    'tip' => '无需安装任何插件',
    'id' => 'joy',
  ),
  'funshion' => 
  array (
    'status' => '1',
    'sort' => '609',
    'from' => 'funshion',
    'show' => '风行视频',
    'des' => 'funshion.com',
    'parse' => '',
    'ps' => '1',
    'tip' => '无需安装任何插件',
    'id' => 'funshion',
  ),
  'wasu' => 
  array (
    'status' => '1',
    'sort' => '607',
    'from' => 'wasu',
    'show' => '华数tv',
    'des' => 'wasu.cn',
    'parse' => '',
    'ps' => '1',
    'tip' => '无需安装任何插件',
    'id' => 'wasu',
  ),
  'tudouhd' => 
  array (
    'status' => '1',
    'sort' => '606',
    'from' => 'tudouhd',
    'show' => '土豆(高清)',
    'des' => 'hd.tudou.com',
    'parse' => '',
    'ps' => '1',
    'tip' => '无需安装任何插件',
    'id' => 'tudouhd',
  ),
  'sohuhd' => 
  array (
    'status' => '1',
    'sort' => '605',
    'from' => 'sohuhd',
    'show' => '搜狐(高清)',
    'des' => 'tv.sohu.com',
    'parse' => '',
    'ps' => '1',
    'tip' => '无需安装任何插件',
    'id' => 'sohuhd',
  ),
  'ku6hd' => 
  array (
    'status' => '1',
    'sort' => '604',
    'from' => 'ku6hd',
    'show' => '酷6(高清)',
    'des' => 'hd.ku6.com',
    'parse' => '',
    'ps' => '1',
    'tip' => '无需安装任何插件',
    'id' => 'ku6hd',
  ),
  'sinahd' => 
  array (
    'status' => '1',
    'sort' => '603',
    'from' => 'sinahd',
    'show' => '新浪(高清)',
    'des' => 'video.sina.com.cn',
    'parse' => '',
    'ps' => '1',
    'tip' => '无需安装任何插件',
    'id' => 'sinahd',
  ),
  'fantasy' => 
  array (
    'status' => '1',
    'sort' => '601',
    'from' => 'fantasy',
    'show' => '范特西云视频',
    'des' => '范特西',
    'parse' => '',
    'ps' => '0',
    'tip' => '无需安装任何插件',
    'id' => 'fantasy',
  ),
  'qq' => 
  array (
    'status' => '1',
    'from' => 'qq',
    'show' => '【腾讯线】',
    'des' => '自动连播',
    'ps' => '1',
    'parse' => '//z1.m1907.cn/?jx=',
    'sort' => '500',
    'tip' => '需要tu.php',
    'id' => 'qq',
  ),
  'youku' => 
  array (
    'status' => '1',
    'from' => 'youku',
    'show' => '【优酷线】',
    'des' => '自动连播',
    'ps' => '1',
    'parse' => '//z1.m1907.cn/?jx=',
    'sort' => '499',
    'tip' => '需要tu.php',
    'id' => 'youku',
  ),
  'qiyi' => 
  array (
    'status' => '1',
    'from' => 'qiyi',
    'show' => '【奇艺线】',
    'des' => '自动连播',
    'ps' => '1',
    'parse' => '//z1.m1907.cn/?jx=',
    'sort' => '498',
    'tip' => '需要tu.php',
    'id' => 'qiyi',
  ),
  'mgtv' => 
  array (
    'status' => '1',
    'from' => 'mgtv',
    'show' => '【芒果线】',
    'des' => '自动连播',
    'ps' => '1',
    'parse' => '//z1.m1907.cn/?jx=',
    'sort' => '497',
    'tip' => '需要tu.php',
    'id' => 'mgtv',
  ),
  'pptv' => 
  array (
    'status' => '1',
    'from' => 'pptv',
    'show' => '【PP线】',
    'des' => '自动连播',
    'ps' => '1',
    'parse' => '//z1.m1907.cn/?jx=',
    'sort' => '496',
    'tip' => '需要tu.php',
    'id' => 'pptv',
  ),
  'sohu' => 
  array (
    'status' => '1',
    'from' => 'sohu',
    'show' => '【搜狐线】',
    'des' => '自动连播',
    'ps' => '1',
    'parse' => '//z1.m1907.cn/?jx=',
    'sort' => '495',
    'tip' => '需要tu.php',
    'id' => 'sohu',
  ),
  'letv' => 
  array (
    'status' => '1',
    'from' => 'letv',
    'show' => '【乐视线】',
    'des' => '自动连播',
    'ps' => '1',
    'parse' => '//z1.m1907.cn/?jx=',
    'sort' => '494',
    'tip' => '需要tu.php',
    'id' => 'letv',
  ),
  'subom3u8' => 
  array (
    'status' => '1',
    'from' => 'subom3u8',
    'show' => '【速播线】',
    'des' => '自动连播',
    'ps' => '1',
    'parse' => '//z1.m1907.cn/?jx=',
    'sort' => '400',
    'tip' => '右下角短时出现水印',
    'id' => 'subom3u8',
  ),
  '172m3u8' => 
  array (
    'status' => '1',
    'from' => '172m3u8',
    'show' => '【七二线】',
    'des' => '自动连播',
    'ps' => '1',
    'parse' => '//z1.m1907.cn/?jx=',
    'sort' => '399',
    'tip' => '右下角常驻水印',
    'id' => '172m3u8',
  ),
  'gqm3u8' => 
  array (
    'status' => '1',
    'from' => 'gqm3u8',
    'show' => '【高清线】',
    'des' => '自动连播',
    'ps' => '1',
    'parse' => '//z1.m1907.cn/?jx=',
    'sort' => '398',
    'tip' => '右下角短时出现水印',
    'id' => 'gqm3u8',
  ),
  'dbm3u8' => 
  array (
    'status' => '1',
    'from' => 'dbm3u8',
    'show' => '【豆瓣线】',
    'des' => '自动连播',
    'ps' => '1',
    'parse' => '//z1.m1907.cn/?jx=',
    'sort' => '397',
    'tip' => '跑马灯,右下角水印',
    'id' => 'dbm3u8',
  ),
  'jpm3u8' => 
  array (
    'status' => '1',
    'from' => 'jpm3u8',
    'show' => '【精品线】',
    'des' => '自动连播',
    'ps' => '1',
    'parse' => '//z1.m1907.cn/?jx=',
    'sort' => '396',
    'tip' => '顶部跑马灯水印',
    'id' => 'jpm3u8',
  ),
  'bjm3u8' => 
  array (
    'status' => '1',
    'from' => 'bjm3u8',
    'show' => '【八戒线】',
    'des' => '自动连播',
    'ps' => '1',
    'parse' => '//z1.m1907.cn/?jx=',
    'sort' => '395',
    'tip' => '顶部跑马灯水印',
    'id' => 'bjm3u8',
  ),
  '27pan' => 
  array (
    'status' => '1',
    'from' => '27pan',
    'show' => '【二七线】',
    'des' => '自动连播',
    'ps' => '1',
    'parse' => '',
    'sort' => '394',
    'tip' => '需要tu.php',
    'id' => '27pan',
  ),
  'jdym3u8' => 
  array (
    'status' => '1',
    'from' => 'jdym3u8',
    'show' => '【极点线】',
    'des' => '',
    'ps' => '1',
    'parse' => '//z1.m1907.cn/?jx=',
    'sort' => '393',
    'tip' => '',
    'id' => 'jdym3u8',
  ),
  'dbyun' => 
  array (
    'status' => '1',
    'from' => 'dbyun',
    'show' => 'dbyun',
    'des' => '',
    'ps' => '1',
    'parse' => '//z1.m1907.cn/?jx=',
    'sort' => '99',
    'tip' => 'dbyun',
    'id' => 'dbyun',
  ),
  'xhgzy' => 
  array (
    'status' => '1',
    'from' => 'xhgzy',
    'show' => '皮皮播',
    'des' => '自动连播',
    'ps' => '1',
    'parse' => '//z1.m1907.cn/?jx=',
    'sort' => '58',
    'tip' => '叉站资源',
    'id' => 'xhgzy',
  ),
  '91yun' => 
  array (
    'status' => '1',
    'from' => '91yun',
    'show' => '虾虾播',
    'des' => '',
    'ps' => '1',
    'parse' => '//z1.m1907.cn/?jx=',
    'sort' => '57',
    'tip' => '',
    'id' => '91yun',
  ),
);